# Generated by Django 4.1.3 on 2022-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='pc_value',
            field=models.FloatField(max_length=200, verbose_name='Price'),
        ),
    ]
