# Generated by Django 4.1.3 on 2022-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.BooleanField(default=False, verbose_name='Main image'),
        ),
    ]
