# Generated by Django 4.1.4 on 2022-12-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_order_order_dt_alter_order_order_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_dt',
            new_name='order_date',
        ),
    ]
